### ISSUE TITLE
Project Ideas?

### ISSUE THREAD

**Issue by GaryLazerFinz** [GaryLazerFinz/ECE-411-Capstone-Practicum#2]
I think the temperature  controlled fan is a good idea. What do you all think?

**Comment by bornhor2** [comment]
That's fine with me.  Would you like it to turn on at a certain temp or change variably with increasing/decreasing temperature?

**Comment by GaryLazerFinz** [comment]
Adjusting the speed is pretty simple with a microcontroller. First step  turn it on at the lowest  acceptable  temp. Then i think its all software after that. Basically turning it on and off real fast adjusts the speed.

**Comment by bornhor2** [comment]
I do have another project idea if it sounds more interesting.. since we are still in the very early stages.  So what about a speedometer for a bike?  Basically it would measure rpms and also distance using some kind of sensor and display... using the circumference of the wheel, etc.  Just another thought... I'm also completely fine with doing the fan or anything else anybody would like to do... just throwing out more options.

**Comment by GaryLazerFinz** [comment]
I built a prototype for the fan but we can switch. No problem. I still need the temp sensor. I personally dont have a bike.  Would we count how many times the tire circulates? I have an infared sensor that could sense reflective tape on the wheel. I can imagine it. I also have code for an arduino to set up the screen sensor, and chip as well. I found an arduino that has an easily removable  chip.  The  arduino makes the display so easy.

**Comment by bornhor2** [comment]
No that's fine... just shooting out more ideas.  I can buy a temp sensor.. I found this complete kit that actually has a sensor and an output pin to drive a motor.... just needs to be programmed. http://www.picaxe.com/Hardware/Project-Kits/Digital-Temperature-Sensor-Kit/

**Comment by GaryLazerFinz** [comment]
Looks like what i got so far. Except, i didnt put an LED, but we can. I scraped together some parts i had. I used two transistors , a diode, 5 resistors, and a place to replace the chips. I used a piece of dot board. I havent tested it  yet, but i will soon.  Maybe we can make it mostly surface mount, and compare it to that one.  The PICAXE can be a surface mount too.

**Comment by GaryLazerFinz** [comment]
How should we finalize the project idea? Communication  is going to be the biggest challenge i can see. Do we need to setup a meeting time?  Everyone needs to decide. I volunteered  us for a fifth member. Please comment here so it is documented. Is github too much?

**Comment by bornhor2** [comment]
I am fine to meet whenever I am free... usually Tues. and Thurs. evenings and most of the day on Mon. and Weds. if I don't have to work. Looks like our next assignment is due the 19th.  If there are any parts from the schematic you're missing or that we might need some extra components, let me know and I'll order them.

**Comment by Xiaoqiao6** [comment]
emmm....it is hard for me to use this website. I still don't know how it works. Will we have a meeting on Tuesday or Wednesday? Ting and I think that temp controller is a good idea.  What can we do in this project?

**Comment by GaryLazerFinz** [comment]
I think the trick is to fork this repository, make a change, and then do a pull request. What would you like to do? Its great that we are documenting this conversation. I think this issue is closed. We all voted for a temp controlled fan.
